language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: g++
      script:
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local .
        - make install -j2
        - ctest -j2 --output-on-failure --timeout 500
      addons:
        apt:
          packages:
            - g++
            - cmake
            - swig
            - python-dev
    - os: osx
      compiler: clang
      script:
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local .
        - make install -j2
        - ctest -j2 --output-on-failure --timeout 500 -E parallel_for
    - os: linux
      compiler: x86_64-w64-mingw32-g++
      script:
        - cmake -DCMAKE_TOOLCHAIN_FILE=build/mingw_cross_toolchain.cmake .
        - make -j2
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
            - cmake
            - make
